---
# This Playbook deploys the applications to the site

- hosts: server
  user: root
  tasks:
  # Groovie sites
  - name: Copy groovie nginx sites file
    template: >
        src=apps/templates/nginx.groovie
        dest=/etc/nginx/sites-available/groovie
        owner=root group=root mode=0644
    notify: restart nginx

  - name: Copy paste nginx sites file
    template: >
        src=apps/templates/nginx.ofcode
        dest=/etc/nginx/sites-available/ofcode
        owner=root group=root mode=0644
    tags: paste
    notify: restart nginx

  - name: Link groovie config to active sites
    file: >
        path=/etc/nginx/sites-enabled/groovie
        src=/etc/nginx/sites-available/groovie
        state=link owner=root group=root
    notify: restart nginx

  - name: Link ofcode config to active sites
    file: >
        path=/etc/nginx/sites-enabled/ofcode
        src=/etc/nginx/sites-available/ofcode
        state=link owner=root group=root
    tags: paste
    notify: restart nginx

  # Paste ofcode
  - name: Add pasteofcode user
    user: name=pasteofcode
    tags: paste

  - name: Add pasteofcode init files
    copy: >
        src=apps/files/${item}.conf
        dest=/etc/init/${item}.conf
        owner=root group=root mode=0644
    with_items:
        - pasteofcode
        - pasteofcode-web

  - name: Check out paste.ofcode.org into its repo
    tags: paste
    git: >
        repo=https://github.com/bbangert/ofcode.git
        dest=/home/pasteofcode/ofcode.org
        force=yes
        version=2792499c95614db640de36578c195ba3870b7ff4

  - name: Chown it all to pasteofcode
    tags: paste
    shell: chown -R pasteofcode /home/pasteofcode

  - name: Run the makefile
    tags: paste
    shell: su - pasteofcode -c 'cd /home/pasteofcode/ofcode.org; make'
    notify: restart pasteofcode

  handlers:
  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
