---
# This Playbook deploys the applications to the site

- hosts: server
  user: freebsd
  sudo: yes
  tasks:

  # Ensure supervisord is installed
  - name: Install supervisor
    pkgng: name=py27-supervisor

  - name: Enable supervisord
    service: name=supervisord enabled=yes state=started

  # Ensure tools are installed
  - name: Install app tools
    pkgng: name=git

  # Do we already have a cert.pem
  - name: Check for ssl cert.pem
    shell: ls -l /etc/ssl/*.pem
    register: certpem

  # Ensure the ssl.cert file is in the place python wants
  - name: Link the ssl cert.pem to the place Python expects
    command: ln -s /usr/local/etc/ssl/cert.pem /etc/ssl/cert.pem
    when: "'cert.pem' not in certpem.stdout"

  # Groovie sites
  - name: Copy groovie nginx sites file
    template: >
        src=apps/templates/nginx.groovie
        dest=/usr/local/etc/nginx/sites/groovie
        owner=root group=wheel mode=0644
    notify: restart nginx

  - name: Copy paste nginx sites file
    template: >
        src=apps/templates/nginx.ofcode
        dest=/usr/local/etc/nginx/sites/ofcode
        owner=root group=wheel mode=0644
    tags: paste
    notify: restart nginx

  # Paste ofcode
  - name: Add pasteofcode user
    user: name=pasteofcode
    tags: paste

  - name: Check out paste.ofcode.org into its repo
    tags: paste
    git: >
        repo=https://github.com/bbangert/ofcode.git
        dest=/home/pasteofcode/ofcode.org
        force=yes
        version=2792499c95614db640de36578c195ba3870b7ff4

  - name: Chown it all to pasteofcode
    tags: paste
    shell: chown -R pasteofcode /home/pasteofcode

  - name: Run the makefile
    tags: paste
    shell: su - pasteofcode -c 'cd /home/pasteofcode/ofcode.org; gmake'

  - name: Copy supervisord config
    copy: >
        src=apps/files/supervisord.conf
        dest=/usr/local/etc/supervisord.conf

  - name: Ensure pasteofcode supervisord
    supervisorctl: name=pasteofcode state=restarted config=/usr/local/etc/supervisord.conf

  handlers:
  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
