---
# This Playbook deploys the applications to the site

- hosts: server
  user: root
  tasks:
  # Sins Against Cinema
  - include: apps/wordpress.yml
    vars:
        domain: sinsagainstcinema.com
        database:
            name: sins
            user: sins
  - include: apps/bind.yml
    vars:
        domain_name: sinsagainstcinema.com
        domain_ttl: 3h
        admin_email: robottaway.gmail.com
        include_google_apps: false

  handlers:
  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
