---
# This Playbook deploys the applications to the site

- hosts: server
  user: freebsd
  sudo: yes
  tasks:

  # IRC packages and server setup
  - name: Install IRC client
    pkgng: name={{item}}
    with_items:
        - irssi
        - irssi-otr
        - irssi-scripts

  - name: Install ircd
    portinstall: name=ircd-hybrid
    environment:
        USE_OPENSSL: "yes"
        NICKLEN: "30"

  - name: Install hybserv
    pkgng: name=hybserv

  - name: Ensure key dir
    file: path=/usr/local/etc/ircd-hybrid/key/ owner=ircd group=ircd mode=0700 state=directory

  - name: Copy keys over
    copy: >
        src=credentials/{{inventory_hostname}}/ircd/{{item}}
        dest=/usr/local/etc/ircd-hybrid/key/{{item}} owner=ircd group=ircd mode=0600
    with_items:
        - "rsa.key"

  - name: Copy pem cert over
    copy: >
        src=credentials/{{inventory_hostname}}/ircd/cert.pem
        dest=/usr/local/etc/ircd-hybrid/key/cert.pem owner=ircd group=ircd mode=0600

  - name: Copy ircd files over
    template: >
         src="apps/templates/ircd/{{item}}.j2"
         dest="/usr/local/etc/ircd-hybrid/{{item}}"
         owner=ircd
         group=ircd
         mode=0770
    with_items:
         - ircd.conf
         - ircd.motd
    notify: restart ircd

  - name: Copy hybserv files over
    template: >
        src="apps/templates/ircd/hybserv.conf"
        dest="/usr/local/hybserv/hybserv.conf"
        owner=hybserv
        group=hybserv
        mode=0660

  - name: Copy chan/nick.db files over
    copy: >
        src="credentials/{{inventory_hostname}}/ircd/{{item}}.db"
        dest="/usr/local/hybserv/{{item}}.db"
        owner=hybserv
        group=hybserv
        mode=0600
    with_items:
        - nick
        - chan
    notify: restart hybserv

  - name: Enable IRC/hybserv servers
    service: name="{{item}}" enabled=true
    with_items:
        - "ircd-hybrid"

  handlers:
  - name: restart ircd
    service: name="ircd-hybrid" state=restarted

  - name: restart hybserv
    service: name="hybserv.sh" state=restarted

  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
