---
# This Playbook deploys the applications to the site

- hosts: server
  user: root
  tasks:

  # IRC packages and server setup
  - name: Install IRC client
    apt: pkg=$item state=latest
    with_items:
      - irssi
      - irssi-plugin-otr
      - irssi-scripts

  - name: Install IRCd/hybsrv package
    apt: pkg=$item state=latest update_cache=yes
    with_items:
      - ircd-hybrid
      - hybserv

  - name: Enable IRC/hybserv servers
    service: name="$item" enabled=true
    with_items:
        - "ircd-hybrid"
        - hybserv

  - name: Ensure key dir
    file: path=/etc/ircd-hybrid/key/ owner=irc group=irc mode=0600 state=directory

  - name: Copy keys over
    copy: >
        src=credentials/${inventory_hostname}/ircd/${item}
        dest=/etc/ircd-hybrid/key/ircd.key owner=irc group=irc mode=0600
    with_items:
        - "rsa.key"
        - "rsa.pub"

  - name: Copy pem cert over
    copy: >
        src=credentials/${inventory_hostname}/ircd/cert.pem
        dest=/etc/ircd-hybrid/key/ircd.pem owner=root group=root mode=0644

  - name: Copy ircd/hybserv apparmor profiles over
    copy: >
        src="apps/files/usr.sbin.${item}"
        dest="/etc/apparmor.d/usr.sbin.${item}"
        owner=root group=root mode=0644
    with_items:
        - hybserv
        - "ircd-hybrid"
    tags: security
    notify:
        - enforce ircd
        - enforce hybserv

  - name: Copy ircd files over
    template: >
         src="apps/templates/ircd/${item}.j2"
         dest="/etc/ircd-hybrid/${item}"
         owner=irc
         group=irc
         mode=0770
    with_items:
         - ircd.conf
         - ircd.motd

  - name: Copy hybserv files over
    template: >
        src="apps/templates/ircd/hybserv.conf"
        dest="/etc/hybserv/hybserv.conf"
        owner=irc
        group=irc
        mode=0660

  - name: Copy chan/nick.db files over
    copy: >
        src="credentials/${inventory_hostname}/ircd/${item}.db"
        dest="/etc/hybserv/${item}.db"
        owner=irc
        group=irc
        mode=0660
    with_items:
        - nick
        - chan

  - name: Check for ircd ufw rule
    shell: ufw status verbose
    tags: security
    register: ircdufw

  - name: Enable ircd port if needed
    shell: ufw allow 6697/tcp
    tags: security
    when: "'6697/tcp' not in ircdufw.stdout"

  handlers:
  - name: enforce ircd
    command: /usr/sbin/aa-enforce /usr/sbin/ircd-hybrid
    notify: restart apparmor

  - name: enforce hybserv
    command: /usr/sbin/aa-enforce /usr/sbin/hybserv
    notify: restart apparmor

  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
