---
# This Playbook deploys the whole application stack in this site.

- hosts: server
  user: root
  tasks:
  - include: roles/common/tasks/main.yml
  - include: roles/webserver/tasks/main.yml
  - include: roles/dbserver/tasks/main.yml
  handlers:
  - include: roles/common/handlers/main.yml
  - include: roles/dbserver/handlers/main.yml
  - include: roles/webserver/handlers/main.yml
