- name: restart bind
  service: name=bind9 state=restarted

- name: rebuild zones
  assemble: src=/root/zonefragments dest=/etc/bind/named.conf.local
  notify: fixup zones

- name: fixup zones
  file: path=/etc/bind/named.conf.local owner=root group=bind mode=0644
