---
# Sets up named files for hosts
# Requires the following vars:
#     domain_name
#     domain_ttl
#     admin_email
#     include_google_apps (set to true or false)
#     records (a list of names like so:)
#         - NAME RECORD_TYPE VALUE

# Example:
#    vars:
#      domain_name: groovie.org
#      domain_ttl: 3h
#      admin_email: ben.groovie.org
#      include_google_apps: false
#      records:
#          - www CNAME groovie.org.
#          - jenkins CNAME groovie.org.

- name: Create zone record for assembly
  tags: bind
  template: src=named.local.frag.j2 dest=/root/zonefragments/${domain_name}
  notify: rebuild zones

- name: Setup record for $domain_name
  tags: bind
  template: src=db.named.j2 dest=/etc/bind/zones/db.${domain_name} owner=root group=bind mode=0644
  notify: restart bind
