---

- include: users.yml

- name: Install the unix basics
  tags: repos
  pkgng: pkg={{item}}
  with_items:
    - screen
    - vim
    - traceroute
    - htop

- name: Update sshd config to use key auth only
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=wheel mode=0644
  notify: restart sshd
