---

- name: add admin accounts
  user: name={{item.user}} group=wheel
  tags: users
  with_items: admins

- name: add admin keys
  authorized_key: user={{item.user}} key="{{item.key}}"
  tags: users
  with_items: admins

- name: add admin keys to root
  authorized_key: user=root key="{{item.key}}"
  tags: users
  with_items: admins
