- name: Setup the nginx PPA
  apt_repository: repo=ppa:nginx/stable

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=yes

- name: Fixup the default nginx host
  copy: src=nginx.default dest=/etc/nginx/sites-available/default owner=root group=root mode=0644

- name: Start nginx
  service: name=nginx state=started enabled=true

- name: Ensure the /var/www dir exists
  file: path=/var/www state=directory owner=www-data group=www-data mode=0644

- name: Check for open port 80
  command: /usr/sbin/ufw status verbose
  register: ufwstatus
  tags: security

- name: Open port 80/443 if needed
  command: /usr/sbin/ufw allow "Nginx Full"
  tags: security
  when: '"Nginx Full" not in ufwstatus'

- include: php.yml
