- name: Install nginx
  pkgng: name=nginx

- name: Copy nginx.conf up
  copy: src=nginx.conf dest=/usr/local/etc/nginx/nginx.conf owner=root group=wheel mode=0644

- name: Ensure nginx log dir exists
  file: path=/var/log/nginx/ owner=root group=wheel mode=0766 state=directory

- name: Ensure sites dir exists
  file: path=/usr/local/etc/nginx/sites/ owner=root group=wheel mode=0700 state=directory

- name: Start nginx
  service: name=nginx state=started enabled=true
