- name: Setup the nginx PPA
  apt_repository: repo=ppa:nginx/stable

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=yes

- name: Start nginx
  service: name=nginx state=started enabled=true

- name: Ensure the /var/www dir exists
  file: path=/var/www state=directory owner=www-data group=www-data mode=0644

- include: php.yml
