- name: Setup the nginx PPA
  apt_repository: repo=ppa:nginx/stable

- name: Install nginx
  apt: pkg=nginx state=latest update_cache=yes

- name: Start nginx
  service: name=nginx state=started enabled=true
