---

- name: Install PHP
  apt: pkg=$item state=latest
  with_items:
    - php5
    - php5-cgi
    - php5-cli
    - php5-common
    - php5-mysql

- name: setup supervisor for php-cgi
  copy: src=roles/webserver/files/php5.cgi.supervisor dest=/etc/supervisor/conf.d/php.conf owner=root group=root mode=0644
  notify:
    - reread supervisor

- name: add php5-cgi to supervisor
  command: /usr/bin/supervisorctl add php5-cgi
