---

- name: Install PHP
  apt: pkg=$item state=latest
  with_items:
    - php5
    - php5-cgi
    - php5-cli
    - php5-common
    - php5-mysql

- name: Copy php-cgi apparmor profile over
  copy: src=usr.bin.php5-cgi dest=/etc/apparmor.d/usr.bin.php5-cgi owner=root group=root mode=0644
  tags: security
  notify:
    - restart apparmor
    - restart php

- name: Setup supervisor for php-cgi
  copy: src=php5.cgi.supervisor dest=/etc/supervisor/conf.d/php.conf owner=root group=root mode=0644
  tags: supervisor
  notify: reread supervisor

- name: Add php5-cgi to supervisor
  command: /usr/bin/supervisorctl add php5-cgi
  tags: supervisor
  when: '"php5-cgi" not in supervisorstatus'

- name: Enable php5 apparmor profile
  command: /usr/sbin/aa-enforce /usr/bin/php5-cgi
  tags: security
  notify:
    - restart apparmor
    - restart php
